// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/evenyosua18/template-project-structure/app/infrastructure/server/grpc/builder"
	user2 "github.com/evenyosua18/template-project-structure/app/repository/example_db/user"
	"github.com/evenyosua18/template-project-structure/app/usecase/user"
)

// Injectors from container.go:

func InitializeUserInteraction() user.IUserInteraction {
	iUserRepository := user2.NewUserRepository()
	iUserInteractionResponse := builder.NewUserBuilder()
	iUserInteraction := user.NewUserInteraction(iUserRepository, iUserInteractionResponse)
	return iUserInteraction
}
